name: 'CI - Test Changed Features'
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - '!**.md'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - '!**.md'
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            atlas: ./**/atlas/**
            buf: ./**/buf/**
            shellcheck: ./**/shellcheck/**

  test:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJSON(needs.detect-changes.outputs.features) }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Install latest devcontainer CLI'
        run: npm install -g @devcontainers/cli
      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated .
